import Link from "next/link";
import { supabaseAdmin } from "@/lib/supabase";

type Order = { id: string; order_number: string; customer_name: string | null; total_cents: number; fulfillment_status: string; created_at: string };
type Product = { id: string; name: string; selling_price_cents: number; status: string; variants?: { stock_quantity: number }[] };
const money = (cents: number) => `₹${new Intl.NumberFormat("en-IN").format(Math.round(cents / 100))}`;
const dateLabel = (date: string) => new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short" }).format(new Date(date));

async function getDashboardData() {
  const empty = { products: 0, published: 0, orders: 0, pending: 0, revenue: 0, lowStock: 0, recentOrders: [] as Order[], productsList: [] as Product[], sales: [] as { label: string; value: number }[] };
  if (!supabaseAdmin) return empty;
  const [productsResult, ordersResult, lowStockResult] = await Promise.all([
    supabaseAdmin.from("catalog_products").select("id, name, selling_price_cents, status, variants:product_variants(stock_quantity)").order("updated_at", { ascending: false }).limit(5),
    supabaseAdmin.from("store_orders").select("id, order_number, customer_name, total_cents, fulfillment_status, created_at").order("created_at", { ascending: false }).limit(100),
    supabaseAdmin.from("product_variants").select("id", { count: "exact", head: true }).lte("stock_quantity", 5),
  ]);
  const products = (productsResult.data ?? []) as Product[];
  const orders = (ordersResult.data ?? []) as Order[];
  const sales = Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - index)); const next = new Date(date); next.setDate(next.getDate() + 1); return { label: new Intl.DateTimeFormat("en-IN", { weekday: "short" }).format(date), value: orders.filter((order) => new Date(order.created_at) >= date && new Date(order.created_at) < next).reduce((sum, order) => sum + order.total_cents, 0) }; });
  return { products: products.length, published: products.filter((product) => product.status === "PUBLISHED").length, orders: orders.length, pending: orders.filter((order) => order.fulfillment_status === "PENDING").length, revenue: orders.reduce((sum, order) => sum + order.total_cents, 0), lowStock: lowStockResult.count ?? 0, recentOrders: orders.slice(0, 5), productsList: products, sales };
}

function Status({ value }: { value: string }) { return <span className={`admin-badge ${value.toLowerCase()}`}><i />{value.toLowerCase().replace("_", " ")}</span>; }

export default async function AdminPage() {
  const data = await getDashboardData();
  const maxSale = Math.max(...data.sales.map((sale) => sale.value), 1);
  return <div className="admin-page dashboard-page">
    <div className="admin-page-heading dashboard-heading"><div><p className="admin-eyebrow">Tuesday, September 1, 2026</p><h1>Good morning, Admin <span>✦</span></h1><p className="admin-subtitle">Here&apos;s what&apos;s happening with your store today.</p></div><Link className="admin-primary" href="/admin/products/new"><span>＋</span> Add product</Link></div>
    {!supabaseAdmin && <div className="admin-notice admin-setup-notice"><span className="admin-notice-icon">!</span><div><strong>Connect your store data</strong><p>Supabase is not configured yet. Add your server credentials to see live orders, inventory and revenue.</p></div><Link href="/admin/settings">Open settings →</Link></div>}
    <div className="admin-stat-grid dashboard-stat-grid"><div className="admin-stat dashboard-stat"><span>Total sales <b className="stat-trend">—</b></span><strong>{money(data.revenue)}</strong><small>All time</small></div><div className="admin-stat dashboard-stat"><span>Orders <b className="stat-trend">—</b></span><strong>{data.orders}</strong><small>All time</small></div><div className="admin-stat dashboard-stat"><span>Products <b className="stat-trend green">—</b></span><strong>{data.products}</strong><small>{data.published} published</small></div><div className="admin-stat dashboard-stat"><span>Low stock <b className="stat-trend amber">!</b></span><strong>{data.lowStock}</strong><small>Needs attention</small></div></div>
    <div className="dashboard-grid"><section className="admin-panel sales-panel"><div className="panel-heading"><div><h2>Sales overview</h2><p>Revenue for the last 7 days</p></div><select aria-label="Sales period" defaultValue="7"><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select></div><div className="sales-total">{money(data.sales.reduce((sum, sale) => sum + sale.value, 0))}</div><div className="sales-chart" aria-label="Sales chart">{data.sales.map((sale) => <div className="sales-column" key={sale.label}><div className="sales-bar" style={{ height: `${Math.max(sale.value / maxSale * 100, sale.value ? 8 : 2)}%` }} title={money(sale.value)} /><span>{sale.label}</span></div>)}</div></section><section className="admin-panel quick-panel"><div className="panel-heading"><div><h2>Quick actions</h2><p>Common store tasks</p></div></div><div className="quick-actions"><Link href="/admin/products/new"><span>＋</span><div><strong>Add a product</strong><small>Create a new catalog item</small></div><b>→</b></Link><Link href="/admin/products"><span>□</span><div><strong>Manage inventory</strong><small>Review stock levels</small></div><b>→</b></Link><Link href="/admin/orders"><span>⌁</span><div><strong>View orders</strong><small>{data.pending} pending fulfillment</small></div><b>→</b></Link></div></section></div>
    <div className="dashboard-grid lower-grid"><section className="admin-panel table-panel"><div className="panel-heading"><div><h2>Recent orders</h2><p>Your latest customer activity</p></div><Link href="/admin/orders" className="admin-text-link">View all →</Link></div>{data.recentOrders.length ? <div className="dashboard-order-list">{data.recentOrders.map((order) => <div className="dashboard-order" key={order.id}><span className="order-avatar">{(order.customer_name ?? "G").slice(0, 1).toUpperCase()}</span><div><strong>{order.order_number}</strong><small>{order.customer_name ?? "Guest customer"} · {dateLabel(order.created_at)}</small></div><strong className="order-value">{money(order.total_cents)}</strong><Status value={order.fulfillment_status} /></div>)}</div> : <div className="admin-empty dashboard-empty"><span className="empty-icon">⌁</span><strong>No orders yet</strong><p>Orders will appear here once your first customer checks out.</p></div>}</section><section className="admin-panel table-panel"><div className="panel-heading"><div><h2>Inventory snapshot</h2><p>Recently updated products</p></div><Link href="/admin/products" className="admin-text-link">View catalog →</Link></div>{data.productsList.length ? <div className="inventory-list">{data.productsList.map((product) => { const stock = (product.variants ?? []).reduce((sum, variant) => sum + variant.stock_quantity, 0); return <div className="inventory-row" key={product.id}><span className="inventory-thumb">{product.name.slice(0, 1)}</span><div><strong>{product.name}</strong><small>{product.status.toLowerCase()}</small></div><span className={stock <= 5 ? "stock-low" : "stock-good"}>{stock} in stock</span></div>; })}</div> : <div className="admin-empty dashboard-empty"><span className="empty-icon">□</span><strong>No products yet</strong><p>Start building your catalog to see inventory health.</p><Link href="/admin/products/new" className="admin-text-link">Add your first product →</Link></div>}</section></div>
  </div>;
}
