"use client";

import { useState } from "react";

type AdminProduct = { id?: string; sku?: string; slug?: string; name?: string; title?: string; description?: string; category?: string; collection?: string; selling_price_cents?: number; color?: string; material?: string; fit?: string; gender?: string; status?: string; featured?: boolean; new_release?: boolean; best_seller?: boolean; variants?: Array<{ size: string; stock_quantity: number }> };

export function ProductForm({ product = {} }: { product?: AdminProduct }) {
  const [message, setMessage] = useState("");
  const [pending, setPending] = useState(false);
  const [values, setValues] = useState({ sku: product.sku ?? "", slug: product.slug ?? "", name: product.name ?? "", title: product.title ?? "", description: product.description ?? "", category: product.category ?? "Trousers", collection: product.collection ?? "Trousers", sellingPrice: product.selling_price_cents ? String(product.selling_price_cents / 100) : "", costPrice: "", sizes: product.variants?.map((variant) => variant.size).join(", ") ?? "", color: product.color ?? "", material: product.material ?? "", fit: product.fit ?? "", gender: product.gender ?? "Men", status: product.status ?? "DRAFT", featured: product.featured ?? false, newRelease: product.new_release ?? false, bestSeller: product.best_seller ?? false });
  function change(event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) { const target = event.target as HTMLInputElement; setValues((current) => ({ ...current, [target.name]: target.type === "checkbox" ? target.checked : target.value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setPending(true); setMessage(""); const response = await fetch(product.id ? `/api/admin/products/${product.id}` : "/api/admin/products", { method: product.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json(); setPending(false); setMessage(response.ok ? "Saved successfully." : result.error ?? "Unable to save product."); }
  return <form className="admin-form" onSubmit={submit}><div className="admin-form-grid">{[["name", "Product name"], ["title", "Product title"], ["sku", "SKU"], ["slug", "Slug"], ["category", "Category"], ["collection", "Collection"], ["sellingPrice", "Selling price (₹)"], ["costPrice", "Cost price (admin only)"], ["sizes", "Sizes, comma separated"], ["color", "Color"], ["material", "Material"], ["fit", "Fit"], ["gender", "Gender"]].map(([name, label]) => <label key={name}>{label}<input name={name} value={String(values[name as keyof typeof values])} onChange={change} type={name === "sellingPrice" || name === "costPrice" ? "number" : "text"} /></label>)}<label className="admin-form-wide">Description<textarea name="description" value={values.description} onChange={change} rows={5} /></label><label>Status<select name="status" value={values.status} onChange={change}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label></div><div className="admin-checks">{[["featured", "Featured"], ["newRelease", "New release"], ["bestSeller", "Best seller"]].map(([name, label]) => <label key={name}><input type="checkbox" name={name} checked={Boolean(values[name as keyof typeof values])} onChange={change} /> {label}</label>)}</div><button className="admin-primary" disabled={pending}>{pending ? "Saving..." : "Save product"}</button>{message ? <p className="admin-form-message">{message}</p> : null}</form>;
}
