import { supabaseAdmin } from "./supabase";
import type { Product } from "./types";

const trousers: Product[] = [
  {
    id: "GFC-TRS-001",
    name: "The Ascot Pleated Trouser",
    title: "The Ascot Pleated Trouser — Ivory White",
    slug: "the-ascot-pleated-trouser",
    description: "The Ascot Pleated Trouser combines a clean tailored silhouette with a relaxed drape, creating a versatile essential designed for elevated everyday dressing.",
    price_cents: 82200,
    image_url: "/products/trousers/GFC-TRS-001/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-001/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-001/03-gallery.png",
      "/products/trousers/GFC-TRS-001/04-gallery.png",
    ],
    sizes: ["30", "32", "34", "36"],
    color: "White",
    material: "Lycra Blend",
    fit: "Relaxed Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: true,
    stock: 12,
    published: true,
  },
  {
    id: "GFC-TRS-002",
    name: "The Riviera Relaxed Trouser – Ivory",
    title: "Giraffe Clothing Riviera Men’s Relaxed Tailored Trousers – Ivory",
    slug: "the-riviera-relaxed-trouser-ivory",
    description: "A refined take on relaxed tailoring. The Riviera Relaxed Trouser combines a clean, flowing silhouette with an easy waistband and understated detailing—designed for effortless everyday sophistication.",
    price_cents: 99200,
    image_url: "/products/trousers/GFC-TRS-002/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-002/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-002/03-gallery.png",
      "/products/trousers/GFC-TRS-002/04-gallery.png",
    ],
    sizes: ["30", "32", "34", "36"],
    color: "Biege",
    material: "Rayon Cotton",
    fit: "Relaxed Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: true,
    stock: 10,
    published: true,
  },
  {
    id: "GFC-TRS-003",
    name: "Noir Wide-Leg Trouser",
    title: "Men's Noir Premium Wide-Leg Tailored Trousers",
    slug: "noir-wide-leg-trouser",
    description: "A refined wide-leg trouser designed with a structured waistband, elegant front pleats and a clean flowing silhouette.",
    price_cents: 95200,
    image_url: "/products/trousers/GFC-TRS-003/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-003/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-003/03-gallery.png",
      "/products/trousers/GFC-TRS-003/04-gallery.png",
    ],
    sizes: ["28", "30", "32", "34"],
    color: "Black",
    material: "Viscose Blend*",
    fit: "Relaxed Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: true,
    stock: 10,
    published: true,
  },
  {
    id: "GFC-TRS-004",
    name: "Men's Premium Grey Textured Pleated Straight-Fit Trousers",
    title: "Giraffe Heritage Pleated Trousers",
    slug: "premium-grey-textured-pleated-straight-fit-trousers",
    description: "A refined pair of grey tailored trousers designed with a subtle textured finish, structured front pleats and a clean straight-leg silhouette.",
    price_cents: 85200,
    image_url: "/products/trousers/GFC-TRS-004/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-004/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-004/03-gallery.png",
      "/products/trousers/GFC-TRS-004/04-gallery.png",
    ],
    sizes: ["30", "32", "34", "36"],
    color: "Grey",
    material: "Rayon Cotton",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 14,
    published: true,
  },
  {
    id: "GFC-TRS-005",
    name: "The Alder Brown Pleated Trousers",
    title: "Giraffe Alder Brown Textured Pleated Wide-Leg Trousers for Men",
    slug: "the-alder-brown-pleated-trousers",
    description: "A refined take on classic tailoring, the Alder Brown Pleated Trousers feature a rich brown textured finish, structured front pleats and an elegant wide-leg silhouette.",
    price_cents: 85200,
    image_url: "/products/trousers/GFC-TRS-005/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-005/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-005/03-gallery.png",
      "/products/trousers/GFC-TRS-005/04-gallery.png",
    ],
    sizes: ["30", "32", "34", "36"],
    color: "Brown",
    material: "Rayon Cotton",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 11,
    published: true,
  },
  {
    id: "GFC-TRS-006",
    name: "Giraffe Signature Flex Trousers – Ivory Beige",
    title: "Men’s Signature Flex Regular-Fit Ivory Beige Trousers",
    slug: "giraffe-signature-flex-trousers-ivory-beige",
    description: "Elevate everyday dressing with the Giraffe Signature Flex Trousers, crafted in a sophisticated ivory-beige tone for a clean, contemporary look.",
    price_cents: 95200,
    image_url: "/products/trousers/GFC-TRS-006/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-006/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-006/03-gallery.png",
      "/products/trousers/GFC-TRS-006/04-gallery.png",
    ],
    sizes: ["30", "32", "34", "36"],
    color: "Ivory Biege",
    material: "Rayon Cotton",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 13,
    published: true,
  },
  {
    id: "GFC-TRS-007",
    name: "Giraffe EaseFlow Relaxed Trousers – Pearl White",
    title: "Men’s EaseFlow Relaxed-Fit Pearl White Drawstring Trousers",
    slug: "giraffe-easeflow-relaxed-trousers-pearl-white",
    description: "Meet the Giraffe EaseFlow Relaxed Trousers, a contemporary essential designed around effortless comfort and clean, minimal styling.",
    price_cents: 62200,
    image_url: "/products/trousers/GFC-TRS-007/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-007/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-007/03-gallery.png",
      "/products/trousers/GFC-TRS-007/04-gallery.png",
    ],
    sizes: ["28", "30", "32", "34", "36"],
    color: "Pearl White",
    material: "Rayon Cotton",
    fit: "Relaxed Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 15,
    published: true,
  },
  {
    id: "GFC-TRS-008",
    name: "Noir Drift Wide-Leg Pants",
    title: "Giraffe Clothing Noir Drift Men’s Textured Wide-Leg Drawstring Pants",
    slug: "noir-drift-wide-leg-pants",
    description: "Make a statement without trying too hard with the Noir Drift Wide-Leg Pants by Giraffe Clothing.",
    price_cents: 65200,
    image_url: "/products/trousers/GFC-TRS-008/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-008/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-008/03-gallery.png",
      "/products/trousers/GFC-TRS-008/04-gallery.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Dark Blue",
    material: "Cotton Blend",
    fit: "Track Pants",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 16,
    published: true,
  },
  {
    id: "GFC-TRS-009",
    name: "Giraffe Relaxed Wide-Leg Trousers – Cloud Grey",
    title: "Giraffe Men’s Cloud Grey Relaxed Wide-Leg Drawstring Trousers",
    slug: "giraffe-relaxed-wide-leg-trousers-cloud-grey",
    description: "Elevate everyday dressing with the Giraffe Relaxed Wide-Leg Trousers in Cloud Grey. Designed with a clean, contemporary silhouette, these trousers feature a relaxed wide-leg cut that creates an effortless drape and modern street-luxury aesthetic.",
    price_cents: 62200,
    image_url: "/products/trousers/GFC-TRS-009/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-009/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-009/03-gallery.png",
      "/products/trousers/GFC-TRS-009/04-gallery.png",
    ],
    sizes: ["S", "M", "L", "XL"],
    color: "Cloud Grey",
    material: "Cotton",
    fit: "Track Pants",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 12,
    published: true,
  },
  {
    id: "GFC-TRS-010",
    name: "Giraffe Noir Relaxed Wide-Leg Trousers",
    title: "Giraffe Men’s Noir Black Relaxed Wide-Leg Drawstring Trousers | Premium Casual Pants",
    slug: "giraffe-noir-relaxed-wide-leg-trousers",
    description: "Introducing the Giraffe Noir Relaxed Wide-Leg Trousers, a refined take on everyday comfort designed for a clean, contemporary wardrobe.",
    price_cents: 56200,
    image_url: "/products/trousers/GFC-TRS-010/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-010/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-010/03-gallery.png",
      "/products/trousers/GFC-TRS-010/04-gallery.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Black",
    material: "Cotton Blend",
    fit: "Track Pants",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 14,
    published: true,
  },
];

const fallbackProducts: Product[] = [
  ...trousers,
  {
    id: "1",
    name: "Sandstone Overshirt",
    slug: "sandstone-overshirt",
    description: "A relaxed everyday overshirt with a structured fit and soft hand feel.",
    price_cents: 7900,
    image_url: "/products/trousers/GFC-TRS-001/01-hanging.png",
    category: "Outerwear",
    is_featured: true,
    stock: 18,
  },
  {
    id: "2",
    name: "Harbor Straight Jeans",
    slug: "harbor-straight-jeans",
    description: "Clean straight-leg denim with a comfortable mid-rise and all-day wearability.",
    price_cents: 6400,
    image_url: "/products/trousers/GFC-TRS-002/01-hanging.png",
    category: "Bottoms",
    is_featured: true,
    stock: 24,
  },
  {
    id: "3",
    name: "Studio Cotton Tee",
    slug: "studio-cotton-tee",
    description: "A heavyweight tee designed to keep its shape while staying soft.",
    price_cents: 3200,
    image_url: "/products/trousers/GFC-TRS-003/01-hanging.png",
    category: "Basics",
    is_featured: false,
    stock: 40,
  },
];

export async function getProducts(): Promise<Product[]> {
  if (!supabaseAdmin) return fallbackProducts;
  const { data, error } = await supabaseAdmin.from("products").select("*").order("is_featured", { ascending: false });
  if (error || !data?.length) return fallbackProducts;
  const merged = [...(data as Product[])];
  for (const product of trousers) {
    if (!merged.some((item) => item.slug === product.slug)) {
      merged.unshift(product);
    }
  }
  return merged;
}

export async function getProductBySlug(slug: string): Promise<Product | null> {
  const products = await getProducts();
  return products.find((product) => product.slug === slug) ?? null;
}
