import { supabaseAdmin } from "./supabase";
import { getCatalogProducts } from "./catalog-db";
import type { Product } from "./types";

const trousers: Product[] = [
  {
    id: "GFC-TRS-001",
    name: "The Ascot Pleated Trouser",
    title: "The Ascot Pleated Trouser — Ivory White",
    slug: "the-ascot-pleated-trouser",
    description: "The Ascot Pleated Trouser combines a clean tailored silhouette with a relaxed drape, creating a versatile essential designed for elevated everyday dressing.",
    price_cents: 82200,
    image_url: "/products/trousers/GFC-TRS-001/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-001/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-001/03-gallery.png",
      "/products/trousers/GFC-TRS-001/04-gallery.png",
    ],
    sizes: ["30", "32", "34", "36"],
    color: "White",
    material: "Lycra Blend",
    fit: "Relaxed Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: true,
    stock: 12,
    published: true,
  },
  {
    id: "GFC-TRS-002",
    name: "The Riviera Relaxed Trouser – Ivory",
    title: "Giraffe Clothing Riviera Men’s Relaxed Tailored Trousers – Ivory",
    slug: "the-riviera-relaxed-trouser-ivory",
    description: "A refined take on relaxed tailoring. The Riviera Relaxed Trouser combines a clean, flowing silhouette with an easy waistband and understated detailing—designed for effortless everyday sophistication.",
    price_cents: 99200,
    image_url: "/products/trousers/GFC-TRS-002/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-002/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-002/03-gallery.png",
      "/products/trousers/GFC-TRS-002/04-gallery.png",
    ],
    sizes: ["30", "32", "34", "36"],
    color: "Biege",
    material: "Rayon Cotton",
    fit: "Relaxed Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: true,
    stock: 10,
    published: true,
  },
  {
    id: "GFC-TRS-003",
    name: "Noir Wide-Leg Trouser",
    title: "Men's Noir Premium Wide-Leg Tailored Trousers",
    slug: "noir-wide-leg-trouser",
    description: "A refined wide-leg trouser designed with a structured waistband, elegant front pleats and a clean flowing silhouette.",
    price_cents: 95200,
    image_url: "/products/trousers/GFC-TRS-003/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-003/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-003/03-gallery.png",
      "/products/trousers/GFC-TRS-003/04-gallery.png",
    ],
    sizes: ["28", "30", "32", "34"],
    color: "Black",
    material: "Viscose Blend*",
    fit: "Relaxed Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: true,
    stock: 10,
    published: true,
  },
  {
    id: "GFC-TRS-004",
    name: "Men's Premium Grey Textured Pleated Straight-Fit Trousers",
    title: "Giraffe Heritage Pleated Trousers",
    slug: "premium-grey-textured-pleated-straight-fit-trousers",
    description: "A refined pair of grey tailored trousers designed with a subtle textured finish, structured front pleats and a clean straight-leg silhouette.",
    price_cents: 85200,
    image_url: "/products/trousers/GFC-TRS-004/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-004/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-004/03-gallery.png",
      "/products/trousers/GFC-TRS-004/04-gallery.png",
    ],
    sizes: ["30", "32", "34", "36"],
    color: "Grey",
    material: "Rayon Cotton",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 14,
    published: true,
  },
  {
    id: "GFC-TRS-005",
    name: "The Alder Brown Pleated Trousers",
    title: "Giraffe Alder Brown Textured Pleated Wide-Leg Trousers for Men",
    slug: "the-alder-brown-pleated-trousers",
    description: "A refined take on classic tailoring, the Alder Brown Pleated Trousers feature a rich brown textured finish, structured front pleats and an elegant wide-leg silhouette.",
    price_cents: 85200,
    image_url: "/products/trousers/GFC-TRS-005/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-005/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-005/03-gallery.png",
      "/products/trousers/GFC-TRS-005/04-gallery.png",
    ],
    sizes: ["30", "32", "34", "36"],
    color: "Brown",
    material: "Rayon Cotton",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 11,
    published: true,
  },
  {
    id: "GFC-TRS-006",
    name: "Giraffe Signature Flex Trousers – Ivory Beige",
    title: "Men’s Signature Flex Regular-Fit Ivory Beige Trousers",
    slug: "giraffe-signature-flex-trousers-ivory-beige",
    description: "Elevate everyday dressing with the Giraffe Signature Flex Trousers, crafted in a sophisticated ivory-beige tone for a clean, contemporary look.",
    price_cents: 95200,
    image_url: "/products/trousers/GFC-TRS-006/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-006/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-006/03-gallery.png",
      "/products/trousers/GFC-TRS-006/04-gallery.png",
    ],
    sizes: ["30", "32", "34", "36"],
    color: "Ivory Biege",
    material: "Rayon Cotton",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 13,
    published: true,
  },
  {
    id: "GFC-TRS-007",
    name: "Giraffe EaseFlow Relaxed Trousers – Pearl White",
    title: "Men’s EaseFlow Relaxed-Fit Pearl White Drawstring Trousers",
    slug: "giraffe-easeflow-relaxed-trousers-pearl-white",
    description: "Meet the Giraffe EaseFlow Relaxed Trousers, a contemporary essential designed around effortless comfort and clean, minimal styling.",
    price_cents: 62200,
    image_url: "/products/trousers/GFC-TRS-007/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-007/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-007/03-gallery.png",
      "/products/trousers/GFC-TRS-007/04-gallery.png",
    ],
    sizes: ["28", "30", "32", "34", "36"],
    color: "Pearl White",
    material: "Rayon Cotton",
    fit: "Relaxed Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 15,
    published: true,
  },
  {
    id: "GFC-TRS-008",
    name: "Noir Drift Wide-Leg Pants",
    title: "Giraffe Clothing Noir Drift Men’s Textured Wide-Leg Drawstring Pants",
    slug: "noir-drift-wide-leg-pants",
    description: "Make a statement without trying too hard with the Noir Drift Wide-Leg Pants by Giraffe Clothing.",
    price_cents: 65200,
    image_url: "/products/trousers/GFC-TRS-008/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-008/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-008/03-gallery.png",
      "/products/trousers/GFC-TRS-008/04-gallery.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Dark Blue",
    material: "Cotton Blend",
    fit: "Track Pants",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 16,
    published: true,
  },
  {
    id: "GFC-TRS-009",
    name: "Giraffe Relaxed Wide-Leg Trousers – Cloud Grey",
    title: "Giraffe Men’s Cloud Grey Relaxed Wide-Leg Drawstring Trousers",
    slug: "giraffe-relaxed-wide-leg-trousers-cloud-grey",
    description: "Elevate everyday dressing with the Giraffe Relaxed Wide-Leg Trousers in Cloud Grey. Designed with a clean, contemporary silhouette, these trousers feature a relaxed wide-leg cut that creates an effortless drape and modern street-luxury aesthetic.",
    price_cents: 62200,
    image_url: "/products/trousers/GFC-TRS-009/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-009/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-009/03-gallery.png",
      "/products/trousers/GFC-TRS-009/04-gallery.png",
    ],
    sizes: ["S", "M", "L", "XL"],
    color: "Cloud Grey",
    material: "Cotton",
    fit: "Track Pants",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 12,
    published: true,
  },
  {
    id: "GFC-TRS-010",
    name: "Giraffe Noir Relaxed Wide-Leg Trousers",
    title: "Giraffe Men’s Noir Black Relaxed Wide-Leg Drawstring Trousers | Premium Casual Pants",
    slug: "giraffe-noir-relaxed-wide-leg-trousers",
    description: "Introducing the Giraffe Noir Relaxed Wide-Leg Trousers, a refined take on everyday comfort designed for a clean, contemporary wardrobe.",
    price_cents: 56200,
    image_url: "/products/trousers/GFC-TRS-010/01-hanging.png",
    hover_image_url: "/products/trousers/GFC-TRS-010/02-standing.png",
    gallery_image_urls: [
      "/products/trousers/GFC-TRS-010/03-gallery.png",
      "/products/trousers/GFC-TRS-010/04-gallery.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Black",
    material: "Cotton Blend",
    fit: "Track Pants",
    gender: "Men",
    stock_status: "In Stock",
    category: "Trousers",
    is_featured: false,
    stock: 14,
    published: true,
  },
];

const polos: Product[] = [
  {
    id: "GFC-POL-001",
    name: "Textured Olive Polo",
    title: "Men's Textured Olive Green Polo Shirt",
    slug: "textured-olive-green-polo-shirt",
    description: "A refined olive green polo shirt for men, crafted with a subtle textured finish, classic collar, and an easy regular fit for polished everyday dressing.",
    price_cents: 62200,
    image_url: "/products/polos/GFC-POL-001/01-flatlay.png",
    hover_image_url: "/products/polos/GFC-POL-001/02-closeup.png",
    gallery_image_urls: ["/products/polos/GFC-POL-001/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Olive Green",
    material: "Textured Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Polos",
    is_featured: true,
    stock: 18,
    published: true,
  },
  {
    id: "GFC-POL-003",
    name: "Navy Contrast Collar Polo",
    title: "Men's Navy Blue Contrast Collar Polo Shirt",
    slug: "navy-blue-contrast-collar-polo-shirt",
    description: "Elevate casual outfits with a navy blue polo shirt finished with a contrasting cream collar and cuffs, a clean placket, and a versatile regular fit.",
    price_cents: 72200,
    image_url: "/products/polos/GFC-POL-003/01-flatlay.png",
    hover_image_url: "/products/polos/GFC-POL-003/02-closeup.png",
    gallery_image_urls: ["/products/polos/GFC-POL-003/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Navy Blue",
    material: "Premium Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Polos",
    is_featured: true,
    stock: 16,
    published: true,
  },
  {
    id: "GFC-POL-004",
    name: "Ivory Contrast Collar Polo",
    title: "Men's Ivory White Contrast Collar Polo Shirt",
    slug: "ivory-white-contrast-collar-polo-shirt",
    description: "Refresh your wardrobe with an ivory white polo shirt detailed with a dark contrast collar and cuffs, a clean silhouette, and easy everyday versatility.",
    price_cents: 72200,
    image_url: "/products/polos/GFC-POL-004/01-flatlay.png",
    hover_image_url: "/products/polos/GFC-POL-004/02-closeup.png",
    gallery_image_urls: ["/products/polos/GFC-POL-004/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Ivory White",
    material: "Premium Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Polos",
    is_featured: true,
    stock: 15,
    published: true,
  },
  {
    id: "GFC-POL-005",
    name: "Black Contrast Collar Polo",
    title: "Men's Black Contrast Collar Textured Polo Shirt",
    slug: "black-contrast-collar-textured-polo-shirt",
    description: "A modern black textured polo shirt with a crisp contrast collar and cuff detail, designed to bring understated structure to everyday menswear.",
    price_cents: 72200,
    image_url: "/products/polos/GFC-POL-005/01-flatlay.png",
    hover_image_url: "/products/polos/GFC-POL-005/02-closeup.png",
    gallery_image_urls: ["/products/polos/GFC-POL-005/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Black",
    material: "Textured Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Polos",
    is_featured: true,
    stock: 14,
    published: true,
  },
  {
    id: "GFC-POL-006",
    name: "Sand Contrast Collar Polo",
    title: "Men's Sand Beige Contrast Collar Polo Shirt",
    slug: "sand-beige-contrast-collar-polo-shirt",
    description: "A sand beige polo shirt with refined dark contrast trim, soft texture, and a relaxed regular fit that moves easily from weekday styling to after-hours plans.",
    price_cents: 72200,
    image_url: "/products/polos/GFC-POL-006/01-flatlay.png",
    hover_image_url: "/products/polos/GFC-POL-006/02-closeup.png",
    gallery_image_urls: ["/products/polos/GFC-POL-006/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Sand Beige",
    material: "Premium Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Polos",
    is_featured: true,
    stock: 17,
    published: true,
  },
  {
    id: "GFC-POL-007",
    name: "Teal Contrast Collar Polo",
    title: "Men's Teal Blue Textured Contrast Collar Polo Shirt",
    slug: "teal-blue-textured-contrast-collar-polo-shirt",
    description: "A statement teal blue polo shirt with a tactile textured weave, contrast collar and cuffs, and a polished regular fit for modern everyday dressing.",
    price_cents: 82200,
    image_url: "/products/polos/GFC-POL-007/01-flatlay.png",
    hover_image_url: "/products/polos/GFC-POL-007/02-closeup.png",
    gallery_image_urls: ["/products/polos/GFC-POL-007/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Teal Blue",
    material: "Premium Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Polos",
    is_featured: true,
    stock: 12,
    published: true,
  },
  {
    id: "GFC-POL-008",
    name: "Burgundy Contrast Collar Polo",
    title: "Men's Burgundy Textured Contrast Collar Polo Shirt",
    slug: "burgundy-textured-contrast-collar-polo-shirt",
    description: "Make everyday dressing more considered with this burgundy polo shirt, featuring a rich textured knit, contrast collar, and comfortable short sleeves.",
    price_cents: 62200,
    image_url: "/products/polos/GFC-POL-008/01-flatlay.png",
    hover_image_url: "/products/polos/GFC-POL-008/02-closeup.png",
    gallery_image_urls: ["/products/polos/GFC-POL-008/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Burgundy",
    material: "Ribbed Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Polos",
    is_featured: true,
    stock: 13,
    published: true,
  },
  {
    id: "GFC-POL-010",
    name: "Brown Ribbed V-Neck Top",
    title: "Men's Brown Ribbed V-Neck Long-Sleeve Polo Top",
    slug: "brown-ribbed-v-neck-long-sleeve-polo-top",
    description: "Discover a richer take on everyday knitwear with this brown ribbed V-neck polo top, designed with long sleeves, a soft structured collar, and a textured finish for elevated casual wear.",
    price_cents: 62200,
    image_url: "/products/polos/GFC-POL-010/01-flatlay.png",
    hover_image_url: "/products/polos/GFC-POL-010/02-closeup.png",
    gallery_image_urls: ["/products/polos/GFC-POL-010/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Brown",
    material: "Textured Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Polos",
    is_featured: true,
    stock: 11,
    published: true,
  },
];

const shirts: Product[] = [
  {
    id: "GFC-SHR-001",
    name: "Ivory Texture Stripe Shirt",
    title: "Men's Ivory Textured Vertical Stripe Shirt",
    slug: "ivory-textured-vertical-stripe-shirt",
    description: "A refined ivory shirt with subtle vertical texture, a classic collar, and an easy regular fit for polished everyday dressing.",
    price_cents: 72200,
    image_url: "/products/shirts/GFC-SHR-001/01-flatlay.png",
    hover_image_url: "/products/shirts/GFC-SHR-001/02-closeup.png",
    gallery_image_urls: ["/products/shirts/GFC-SHR-001/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Ivory",
    material: "Textured Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Shirts",
    is_featured: true,
    stock: 16,
    published: true,
  },
  {
    id: "GFC-SHR-002",
    name: "Ivory Textured Resort Shirt",
    title: "Men's Ivory Textured Short-Sleeve Resort Shirt",
    slug: "ivory-textured-short-sleeve-resort-shirt",
    description: "An easy ivory resort shirt with a tactile vertical texture, open collar, short sleeves, and a relaxed silhouette for warm-weather dressing.",
    price_cents: 72200,
    image_url: "/products/shirts/GFC-SHR-002/01-flatlay.png",
    hover_image_url: "/products/shirts/GFC-SHR-002/02-closeup.png",
    gallery_image_urls: ["/products/shirts/GFC-SHR-002/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Ivory",
    material: "Textured Cotton Blend",
    fit: "Relaxed Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Shirts",
    is_featured: true,
    stock: 15,
    published: true,
  },
  {
    id: "GFC-SHR-003",
    name: "Navy Striped Resort Shirt",
    title: "Men's Navy Blue Textured Stripe Resort Shirt",
    slug: "navy-blue-textured-stripe-resort-shirt",
    description: "A deep navy short-sleeve shirt with distinctive vertical stripe detailing, an open resort collar, and a relaxed silhouette.",
    price_cents: 72200,
    image_url: "/products/shirts/GFC-SHR-003/01-flatlay.png",
    hover_image_url: "/products/shirts/GFC-SHR-003/02-closeup.png",
    gallery_image_urls: ["/products/shirts/GFC-SHR-003/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Navy Blue",
    material: "Textured Cotton Blend",
    fit: "Relaxed Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Shirts",
    is_featured: true,
    stock: 14,
    published: true,
  },
  {
    id: "GFC-SHR-004",
    name: "Red Check Overshirt",
    title: "Men's Red and Ivory Checked Long-Sleeve Shirt",
    slug: "red-ivory-checked-long-sleeve-shirt",
    description: "A bold red and ivory checked shirt in a textured weave, finished with long sleeves, a classic collar, and a clean curved hem.",
    price_cents: 82200,
    image_url: "/products/shirts/GFC-SHR-004/01-flatlay.png",
    hover_image_url: "/products/shirts/GFC-SHR-004/02-closeup.png",
    gallery_image_urls: ["/products/shirts/GFC-SHR-004/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Red",
    material: "Textured Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Shirts",
    is_featured: true,
    stock: 12,
    published: true,
  },
  {
    id: "GFC-SHR-005",
    name: "Forest Green Check Shirt",
    title: "Men's Forest Green and Ivory Checked Shirt",
    slug: "forest-green-ivory-checked-shirt",
    description: "A considered forest green checked shirt with a tactile finish, full sleeves, and an easy shape made for layered everyday styling.",
    price_cents: 82200,
    image_url: "/products/shirts/GFC-SHR-005/01-flatlay.png",
    hover_image_url: "/products/shirts/GFC-SHR-005/02-closeup.png",
    gallery_image_urls: ["/products/shirts/GFC-SHR-005/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Forest Green",
    material: "Textured Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Shirts",
    is_featured: true,
    stock: 13,
    published: true,
  },
  {
    id: "GFC-SHR-006",
    name: "Blue Check Shirt",
    title: "Men's Sky Blue and Ivory Checked Shirt",
    slug: "sky-blue-ivory-checked-shirt",
    description: "A fresh sky blue checked shirt with a softly textured finish, classic collar, and comfortable regular fit.",
    price_cents: 82200,
    image_url: "/products/shirts/GFC-SHR-006/01-flatlay.png",
    hover_image_url: "/products/shirts/GFC-SHR-006/02-closeup.png",
    gallery_image_urls: ["/products/shirts/GFC-SHR-006/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Sky Blue",
    material: "Textured Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Shirts",
    is_featured: true,
    stock: 15,
    published: true,
  },
  {
    id: "GFC-SHR-007",
    name: "Rust Check Shirt",
    title: "Men's Rust Orange and Ivory Checked Shirt",
    slug: "rust-orange-ivory-checked-shirt",
    description: "A warm rust checked shirt with a lightweight textured hand feel, classic collar, and versatile long-sleeve silhouette.",
    price_cents: 82200,
    image_url: "/products/shirts/GFC-SHR-007/01-flatlay.png",
    hover_image_url: "/products/shirts/GFC-SHR-007/02-closeup.png",
    gallery_image_urls: ["/products/shirts/GFC-SHR-007/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Rust Orange",
    material: "Textured Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Shirts",
    is_featured: true,
    stock: 11,
    published: true,
  },
  {
    id: "GFC-SHR-008",
    name: "Monochrome Check Shirt",
    title: "Men's Black and Grey Checked Shirt",
    slug: "black-grey-checked-shirt",
    description: "A monochrome checked shirt designed with a textured weave, crisp collar, and a clean silhouette that works across the week.",
    price_cents: 82200,
    image_url: "/products/shirts/GFC-SHR-008/01-flatlay.png",
    hover_image_url: "/products/shirts/GFC-SHR-008/02-closeup.png",
    gallery_image_urls: ["/products/shirts/GFC-SHR-008/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Black and Grey",
    material: "Textured Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Shirts",
    is_featured: true,
    stock: 14,
    published: true,
  },
  {
    id: "GFC-SHR-009",
    name: "Pink Sunflower Shirt",
    title: "Men's Pink Striped Sunflower Embroidered Shirt",
    slug: "pink-striped-sunflower-embroidered-shirt",
    description: "A playful pink striped shirt with sunflower embroidery, a classic collar, and statement cuffs for expressive everyday dressing.",
    price_cents: 85200,
    image_url: "/products/shirts/GFC-SHR-009/01-flatlay.png",
    hover_image_url: "/products/shirts/GFC-SHR-009/02-closeup.png",
    gallery_image_urls: ["/products/shirts/GFC-SHR-009/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Pink",
    material: "Cotton",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Shirts",
    is_featured: true,
    stock: 10,
    published: true,
  },
  {
    id: "GFC-SHR-010",
    name: "Blue Stripe Shirt",
    title: "Men's Light Blue Vertical Stripe Shirt",
    slug: "light-blue-vertical-stripe-shirt",
    description: "A timeless light blue striped shirt with clean white cuffs, a classic collar, and a polished regular fit.",
    price_cents: 72200,
    image_url: "/products/shirts/GFC-SHR-010/01-flatlay.png",
    hover_image_url: "/products/shirts/GFC-SHR-010/02-closeup.png",
    gallery_image_urls: ["/products/shirts/GFC-SHR-010/03-full.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Light Blue",
    material: "Cotton Blend",
    fit: "Regular Fit",
    gender: "Men",
    stock_status: "In Stock",
    category: "Shirts",
    is_featured: true,
    stock: 17,
    published: true,
  },
];

export const fallbackProducts: Product[] = [
  ...shirts,
  ...polos,
  ...trousers,
  {
    id: "1",
    name: "Sandstone Overshirt",
    slug: "sandstone-overshirt",
    description: "A relaxed everyday overshirt with a structured fit and soft hand feel.",
    price_cents: 7900,
    image_url: "/products/trousers/GFC-TRS-001/01-hanging.png",
    category: "Outerwear",
    is_featured: true,
    stock: 18,
  },
  {
    id: "2",
    name: "Harbor Straight Jeans",
    slug: "harbor-straight-jeans",
    description: "Clean straight-leg denim with a comfortable mid-rise and all-day wearability.",
    price_cents: 6400,
    image_url: "/products/trousers/GFC-TRS-002/01-hanging.png",
    category: "Bottoms",
    is_featured: true,
    stock: 24,
  },
  {
    id: "3",
    name: "Studio Cotton Tee",
    slug: "studio-cotton-tee",
    description: "A heavyweight tee designed to keep its shape while staying soft.",
    price_cents: 3200,
    image_url: "/products/trousers/GFC-TRS-003/01-hanging.png",
    category: "Basics",
    is_featured: false,
    stock: 40,
  },
];

export function getFallbackProducts() {
  return fallbackProducts;
}

export async function getProducts(): Promise<Product[]> {
  const catalogProducts = await getCatalogProducts();
  if (catalogProducts) {
    const staticProducts = [...shirts, ...polos];
    const staticIds = new Set(staticProducts.map((product) => product.id));
    const staticSlugs = new Set(staticProducts.map((product) => product.slug));
    return [...staticProducts, ...catalogProducts.filter((product) => !staticIds.has(product.id) && !staticSlugs.has(product.slug))];
  }
  if (!supabaseAdmin) return fallbackProducts;
  const { data, error } = await supabaseAdmin.from("products").select("*").order("is_featured", { ascending: false });
  if (error || !data?.length) return fallbackProducts;
  const merged = [...(data as Product[])];
  for (const product of [...shirts, ...polos, ...trousers]) {
    if (!merged.some((item) => item.slug === product.slug)) {
      merged.unshift(product);
    }
  }
  return merged;
}

export async function getProductBySlug(slug: string): Promise<Product | null> {
  const products = await getProducts();
  return products.find((product) => product.slug === slug) ?? null;
}
